### ISSUE TITLE
Augeas::get cannot indicate that there were mulitple matching nodes

### ISSUE THREAD

**Issue by panicbit** [hercules-team/rust-augeas#7]

**Comment by lutter** [comment]
That's considered an error in the Augeas API, and it looks like we are properly returning an `Err(ManyMatches)` in that case.

**Comment by panicbit** [comment]
As far as I know we don't because we are ignoring the result of aug_get, unless the error is also stored as global augeas error.

**Comment by lutter** [comment]
Yes, `aug_get` also reports that as `EMMATCH` through `aug_error` etc.
